# Generated by Django 3.2.7 on 2021-09-14 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_auto_20210914_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 9, 14, 10, 51, 15, 378030, tzinfo=utc)),
        ),
    ]
