# Generated by Django 3.2.7 on 2021-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0004_alter_message_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
