# Generated by Django 3.2.7 on 2021-09-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0005_message_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(max_length=1000000),
        ),
    ]
