# Generated by Django 3.2.7 on 2021-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0006_alter_message_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(max_length=10000),
        ),
    ]
