# Generated by Django 3.2.7 on 2021-09-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0007_auto_20210914_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='freeze',
            field=models.BooleanField(default=False),
        ),
    ]
