# Generated by Django 3.2.7 on 2021-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0009_auto_20210914_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
